In [2]:
import numpy as np
from math import sqrt
import qiskit

Single qubit 

In [3]:
qubits = {
    "|0\u27E9" : np.array([1,0]),
    "|1\u27E9" : np.array([0,1]),
    "(|0\u27E9+|1\u27E9)/\u221a2":1/sqrt(2)*np.
    array([1,1])
}

In [4]:
for q in qubits:
    print(q , qubits[q].round(3))

|0⟩ [1 0]
|1⟩ [0 1]
(|0⟩+|1⟩)/√2 [0.707 0.707]


In [5]:
gates = {
    "id" : np.array([[1,0],[0,1]]),
    "x" : np.array([[0,1],[1,0]]),
    "h" : 1/sqrt(2) * np.array([[1,1],[1,-1]])
}

In [6]:
for g in gates:
    for q in qubits:
        print(np.dot(gates[g],qubits[q].round(3)))

[1 0]
[0 1]
[0.707 0.707]
[0 1]
[1 0]
[0.707 0.707]
[0.70710678 0.70710678]
[ 0.70710678 -0.70710678]
[9.99848989e-01 6.74518966e-18]


Two-qubit

In [7]:
two_qubit = {
    "|00\u27E9" : np.array([1,0,0,0]),
    "|01\u27E9" : np.array([0,1,0,0]),
    "|10\u27E9" : np.array([0,0,1,0]),
    "|11\u27E9" : np.array([0,0,0,1])
}

In [9]:
two_gates = {
    "cx":np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]]),
    "swap or triple cnot":np.array([[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]])
}

In [ ]:
for gates in two_gates:
    for q in two_qubit:
        print(np.dot(two_gates[gates],two_qubit[q]))

[1 0 0 0]
[0 1 0 0]
[0 0 0 1]
[0 0 1 0]
[1 0 0 0]
[0 0 1 0]
[0 1 0 0]
[0 0 0 1]
